[package]
name = "chip-8"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
fastrand = "2.1.0"
sdl2 = "0.37.0"
xflags = "0.3.2"

[profile.release]
lto = "fat"
panic = "abort"
opt-level = 3
debug = "full"
codegen-units = 1
